version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/srv/app/

  db:
    image: mysql:5.7
    container_name: dewaarde_mysql
    volumes:
       - ./database:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dewaarde
      MYSQL_USER: dewaarde
      MYSQL_PASSWORD: dewaarde

  app-db:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - .:/srv/app/

